# syntax=docker/dockerfile:1

ARG GO_VERSION=1.21.3
FROM golang:${GO_VERSION}-bullseye AS build

RUN apt-get update && apt-get upgrade -y && \
    apt-get install -y default-mysql-client ca-certificates && \
    apt-get install -y ruby && \
    gem install license_finder && \
    rm -rf /var/lib/apt/lists/*


WORKDIR /airbyte-source
COPY . .

RUN go mod download
RUN go build -trimpath -o /connect
