# syntax=docker/dockerfile:1

ARG GO_VERSION=1.22.2
FROM pscale.dev/wolfi-prod/go:${GO_VERSION} AS build

RUN apk add --no-cache openssl libxcrypt ruby-3.2
RUN gem install license_finder

ENTRYPOINT []
WORKDIR /airbyte-source
COPY . .

RUN go mod download
RUN CGO_ENABLED=0 go build -trimpath -ldflags="-s -w" -o /connect
