# syntax=docker/dockerfile:1
FROM --platform=$BUILDPLATFORM pscale.dev/wolfi-prod/base:latest
COPY connect /usr/local/bin/
ENV AIRBYTE_ENTRYPOINT "/usr/local/bin/connect"
ENTRYPOINT ["/usr/local/bin/connect"]
