// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.20.1
// source: vtgateservice.proto

package vtgateservice

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Vitess_VStream_FullMethodName = "/vtgateservice.Vitess/VStream"
)

// VitessClient is the client API for Vitess service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type VitessClient interface {
	VStream(ctx context.Context, in *VStreamRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[VStreamResponse], error)
}

type vitessClient struct {
	cc grpc.ClientConnInterface
}

func NewVitessClient(cc grpc.ClientConnInterface) VitessClient {
	return &vitessClient{cc}
}

func (c *vitessClient) VStream(ctx context.Context, in *VStreamRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[VStreamResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &Vitess_ServiceDesc.Streams[0], Vitess_VStream_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[VStreamRequest, VStreamResponse]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Vitess_VStreamClient = grpc.ServerStreamingClient[VStreamResponse]

// VitessServer is the server API for Vitess service.
// All implementations should embed UnimplementedVitessServer
// for forward compatibility.
type VitessServer interface {
	VStream(*VStreamRequest, grpc.ServerStreamingServer[VStreamResponse]) error
}

// UnimplementedVitessServer should be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedVitessServer struct{}

func (UnimplementedVitessServer) VStream(*VStreamRequest, grpc.ServerStreamingServer[VStreamResponse]) error {
	return status.Errorf(codes.Unimplemented, "method VStream not implemented")
}
func (UnimplementedVitessServer) testEmbeddedByValue() {}

// UnsafeVitessServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to VitessServer will
// result in compilation errors.
type UnsafeVitessServer interface {
	mustEmbedUnimplementedVitessServer()
}

func RegisterVitessServer(s grpc.ServiceRegistrar, srv VitessServer) {
	// If the following call pancis, it indicates UnimplementedVitessServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Vitess_ServiceDesc, srv)
}

func _Vitess_VStream_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(VStreamRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(VitessServer).VStream(m, &grpc.GenericServerStream[VStreamRequest, VStreamResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Vitess_VStreamServer = grpc.ServerStreamingServer[VStreamResponse]

// Vitess_ServiceDesc is the grpc.ServiceDesc for Vitess service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Vitess_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "vtgateservice.Vitess",
	HandlerType: (*VitessServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "VStream",
			Handler:       _Vitess_VStream_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "vtgateservice.proto",
}
