// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.1
// 	protoc        v3.20.1
// source: psdbconnect.v1alpha1.proto

package psdbconnectv1alpha1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	query "vitess.io/vitess/go/vt/proto/query"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

//enumcheck:exhaustive
type TabletType int32

const (
	// REPLICA replicates from primary. It is used to serve live traffic.
	// A REPLICA can be promoted to PRIMARY. A demoted PRIMARY will go to REPLICA.
	TabletType_replica TabletType = 0
	// PRIMARY is the primary server for the shard. Only PRIMARY allows DMLs.
	TabletType_primary TabletType = 1
	// RDONLY (old name) / BATCH (new name) is used to serve traffic for
	// long-running jobs. It is a separate type from REPLICA so
	// long-running queries don't affect web-like traffic.
	TabletType_read_only TabletType = 2
	TabletType_batch     TabletType = 2
)

// Enum value maps for TabletType.
var (
	TabletType_name = map[int32]string{
		0: "replica",
		1: "primary",
		2: "read_only",
		// Duplicate value: 2: "batch",
	}
	TabletType_value = map[string]int32{
		"replica":   0,
		"primary":   1,
		"read_only": 2,
		"batch":     2,
	}
)

func (x TabletType) Enum() *TabletType {
	p := new(TabletType)
	*p = x
	return p
}

func (x TabletType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TabletType) Descriptor() protoreflect.EnumDescriptor {
	return file_psdbconnect_v1alpha1_proto_enumTypes[0].Descriptor()
}

func (TabletType) Type() protoreflect.EnumType {
	return &file_psdbconnect_v1alpha1_proto_enumTypes[0]
}

func (x TabletType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TabletType.Descriptor instead.
func (TabletType) EnumDescriptor() ([]byte, []int) {
	return file_psdbconnect_v1alpha1_proto_rawDescGZIP(), []int{0}
}

type DeletedRow struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Result *query.QueryResult `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
}

func (x *DeletedRow) Reset() {
	*x = DeletedRow{}
	if protoimpl.UnsafeEnabled {
		mi := &file_psdbconnect_v1alpha1_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeletedRow) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeletedRow) ProtoMessage() {}

func (x *DeletedRow) ProtoReflect() protoreflect.Message {
	mi := &file_psdbconnect_v1alpha1_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeletedRow.ProtoReflect.Descriptor instead.
func (*DeletedRow) Descriptor() ([]byte, []int) {
	return file_psdbconnect_v1alpha1_proto_rawDescGZIP(), []int{0}
}

func (x *DeletedRow) GetResult() *query.QueryResult {
	if x != nil {
		return x.Result
	}
	return nil
}

type UpdatedRow struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Before *query.QueryResult `protobuf:"bytes,1,opt,name=before,proto3" json:"before,omitempty"`
	After  *query.QueryResult `protobuf:"bytes,2,opt,name=after,proto3" json:"after,omitempty"`
}

func (x *UpdatedRow) Reset() {
	*x = UpdatedRow{}
	if protoimpl.UnsafeEnabled {
		mi := &file_psdbconnect_v1alpha1_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdatedRow) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdatedRow) ProtoMessage() {}

func (x *UpdatedRow) ProtoReflect() protoreflect.Message {
	mi := &file_psdbconnect_v1alpha1_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdatedRow.ProtoReflect.Descriptor instead.
func (*UpdatedRow) Descriptor() ([]byte, []int) {
	return file_psdbconnect_v1alpha1_proto_rawDescGZIP(), []int{1}
}

func (x *UpdatedRow) GetBefore() *query.QueryResult {
	if x != nil {
		return x.Before
	}
	return nil
}

func (x *UpdatedRow) GetAfter() *query.QueryResult {
	if x != nil {
		return x.After
	}
	return nil
}

type TableCursor struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Shard       string             `protobuf:"bytes,1,opt,name=shard,proto3" json:"shard,omitempty"`
	Keyspace    string             `protobuf:"bytes,2,opt,name=keyspace,proto3" json:"keyspace,omitempty"`
	Position    string             `protobuf:"bytes,3,opt,name=position,proto3" json:"position,omitempty"`
	LastKnownPk *query.QueryResult `protobuf:"bytes,4,opt,name=last_known_pk,json=lastKnownPk,proto3" json:"last_known_pk,omitempty"`
}

func (x *TableCursor) Reset() {
	*x = TableCursor{}
	if protoimpl.UnsafeEnabled {
		mi := &file_psdbconnect_v1alpha1_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TableCursor) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TableCursor) ProtoMessage() {}

func (x *TableCursor) ProtoReflect() protoreflect.Message {
	mi := &file_psdbconnect_v1alpha1_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TableCursor.ProtoReflect.Descriptor instead.
func (*TableCursor) Descriptor() ([]byte, []int) {
	return file_psdbconnect_v1alpha1_proto_rawDescGZIP(), []int{2}
}

func (x *TableCursor) GetShard() string {
	if x != nil {
		return x.Shard
	}
	return ""
}

func (x *TableCursor) GetKeyspace() string {
	if x != nil {
		return x.Keyspace
	}
	return ""
}

func (x *TableCursor) GetPosition() string {
	if x != nil {
		return x.Position
	}
	return ""
}

func (x *TableCursor) GetLastKnownPk() *query.QueryResult {
	if x != nil {
		return x.LastKnownPk
	}
	return nil
}

var File_psdbconnect_v1alpha1_proto protoreflect.FileDescriptor

var file_psdbconnect_v1alpha1_proto_rawDesc = []byte{
	0x0a, 0x1a, 0x70, 0x73, 0x64, 0x62, 0x63, 0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74, 0x2e, 0x76, 0x31,
	0x61, 0x6c, 0x70, 0x68, 0x61, 0x31, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x14, 0x70, 0x73,
	0x64, 0x62, 0x63, 0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74, 0x2e, 0x76, 0x31, 0x61, 0x6c, 0x70, 0x68,
	0x61, 0x31, 0x1a, 0x0b, 0x71, 0x75, 0x65, 0x72, 0x79, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22,
	0x38, 0x0a, 0x0a, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x64, 0x52, 0x6f, 0x77, 0x12, 0x2a, 0x0a,
	0x06, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x12, 0x2e,
	0x71, 0x75, 0x65, 0x72, 0x79, 0x2e, 0x51, 0x75, 0x65, 0x72, 0x79, 0x52, 0x65, 0x73, 0x75, 0x6c,
	0x74, 0x52, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x22, 0x62, 0x0a, 0x0a, 0x55, 0x70, 0x64,
	0x61, 0x74, 0x65, 0x64, 0x52, 0x6f, 0x77, 0x12, 0x2a, 0x0a, 0x06, 0x62, 0x65, 0x66, 0x6f, 0x72,
	0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x12, 0x2e, 0x71, 0x75, 0x65, 0x72, 0x79, 0x2e,
	0x51, 0x75, 0x65, 0x72, 0x79, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x52, 0x06, 0x62, 0x65, 0x66,
	0x6f, 0x72, 0x65, 0x12, 0x28, 0x0a, 0x05, 0x61, 0x66, 0x74, 0x65, 0x72, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x12, 0x2e, 0x71, 0x75, 0x65, 0x72, 0x79, 0x2e, 0x51, 0x75, 0x65, 0x72, 0x79,
	0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x52, 0x05, 0x61, 0x66, 0x74, 0x65, 0x72, 0x22, 0x93, 0x01,
	0x0a, 0x0b, 0x54, 0x61, 0x62, 0x6c, 0x65, 0x43, 0x75, 0x72, 0x73, 0x6f, 0x72, 0x12, 0x14, 0x0a,
	0x05, 0x73, 0x68, 0x61, 0x72, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x73, 0x68,
	0x61, 0x72, 0x64, 0x12, 0x1a, 0x0a, 0x08, 0x6b, 0x65, 0x79, 0x73, 0x70, 0x61, 0x63, 0x65, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x6b, 0x65, 0x79, 0x73, 0x70, 0x61, 0x63, 0x65, 0x12,
	0x1a, 0x0a, 0x08, 0x70, 0x6f, 0x73, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x08, 0x70, 0x6f, 0x73, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x36, 0x0a, 0x0d, 0x6c,
	0x61, 0x73, 0x74, 0x5f, 0x6b, 0x6e, 0x6f, 0x77, 0x6e, 0x5f, 0x70, 0x6b, 0x18, 0x04, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x12, 0x2e, 0x71, 0x75, 0x65, 0x72, 0x79, 0x2e, 0x51, 0x75, 0x65, 0x72, 0x79,
	0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x52, 0x0b, 0x6c, 0x61, 0x73, 0x74, 0x4b, 0x6e, 0x6f, 0x77,
	0x6e, 0x50, 0x6b, 0x2a, 0x44, 0x0a, 0x0a, 0x54, 0x61, 0x62, 0x6c, 0x65, 0x74, 0x54, 0x79, 0x70,
	0x65, 0x12, 0x0b, 0x0a, 0x07, 0x72, 0x65, 0x70, 0x6c, 0x69, 0x63, 0x61, 0x10, 0x00, 0x12, 0x0b,
	0x0a, 0x07, 0x70, 0x72, 0x69, 0x6d, 0x61, 0x72, 0x79, 0x10, 0x01, 0x12, 0x0d, 0x0a, 0x09, 0x72,
	0x65, 0x61, 0x64, 0x5f, 0x6f, 0x6e, 0x6c, 0x79, 0x10, 0x02, 0x12, 0x09, 0x0a, 0x05, 0x62, 0x61,
	0x74, 0x63, 0x68, 0x10, 0x02, 0x1a, 0x02, 0x10, 0x01, 0x42, 0x56, 0x5a, 0x54, 0x67, 0x69, 0x74,
	0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x70, 0x6c, 0x61, 0x6e, 0x65, 0x74, 0x73, 0x63,
	0x61, 0x6c, 0x65, 0x2f, 0x61, 0x69, 0x72, 0x62, 0x79, 0x74, 0x65, 0x2d, 0x73, 0x6f, 0x75, 0x72,
	0x63, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x70, 0x73, 0x64, 0x62, 0x63, 0x6f, 0x6e,
	0x6e, 0x65, 0x63, 0x74, 0x2f, 0x76, 0x31, 0x61, 0x6c, 0x70, 0x68, 0x61, 0x31, 0x3b, 0x70, 0x73,
	0x64, 0x62, 0x63, 0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74, 0x76, 0x31, 0x61, 0x6c, 0x70, 0x68, 0x61,
	0x31, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_psdbconnect_v1alpha1_proto_rawDescOnce sync.Once
	file_psdbconnect_v1alpha1_proto_rawDescData = file_psdbconnect_v1alpha1_proto_rawDesc
)

func file_psdbconnect_v1alpha1_proto_rawDescGZIP() []byte {
	file_psdbconnect_v1alpha1_proto_rawDescOnce.Do(func() {
		file_psdbconnect_v1alpha1_proto_rawDescData = protoimpl.X.CompressGZIP(file_psdbconnect_v1alpha1_proto_rawDescData)
	})
	return file_psdbconnect_v1alpha1_proto_rawDescData
}

var file_psdbconnect_v1alpha1_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_psdbconnect_v1alpha1_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_psdbconnect_v1alpha1_proto_goTypes = []interface{}{
	(TabletType)(0),           // 0: psdbconnect.v1alpha1.TabletType
	(*DeletedRow)(nil),        // 1: psdbconnect.v1alpha1.DeletedRow
	(*UpdatedRow)(nil),        // 2: psdbconnect.v1alpha1.UpdatedRow
	(*TableCursor)(nil),       // 3: psdbconnect.v1alpha1.TableCursor
	(*query.QueryResult)(nil), // 4: query.QueryResult
}
var file_psdbconnect_v1alpha1_proto_depIdxs = []int32{
	4, // 0: psdbconnect.v1alpha1.DeletedRow.result:type_name -> query.QueryResult
	4, // 1: psdbconnect.v1alpha1.UpdatedRow.before:type_name -> query.QueryResult
	4, // 2: psdbconnect.v1alpha1.UpdatedRow.after:type_name -> query.QueryResult
	4, // 3: psdbconnect.v1alpha1.TableCursor.last_known_pk:type_name -> query.QueryResult
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_psdbconnect_v1alpha1_proto_init() }
func file_psdbconnect_v1alpha1_proto_init() {
	if File_psdbconnect_v1alpha1_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_psdbconnect_v1alpha1_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeletedRow); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_psdbconnect_v1alpha1_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdatedRow); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_psdbconnect_v1alpha1_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TableCursor); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_psdbconnect_v1alpha1_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_psdbconnect_v1alpha1_proto_goTypes,
		DependencyIndexes: file_psdbconnect_v1alpha1_proto_depIdxs,
		EnumInfos:         file_psdbconnect_v1alpha1_proto_enumTypes,
		MessageInfos:      file_psdbconnect_v1alpha1_proto_msgTypes,
	}.Build()
	File_psdbconnect_v1alpha1_proto = out.File
	file_psdbconnect_v1alpha1_proto_rawDesc = nil
	file_psdbconnect_v1alpha1_proto_goTypes = nil
	file_psdbconnect_v1alpha1_proto_depIdxs = nil
}
