// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v3.20.1
// source: psdbconnect.v1alpha1.proto

package psdbconnectv1alpha1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
	query "vitess.io/vitess/go/vt/proto/query"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

//enumcheck:exhaustive
type TabletType int32

const (
	// REPLICA replicates from primary. It is used to serve live traffic.
	// A REPLICA can be promoted to PRIMARY. A demoted PRIMARY will go to REPLICA.
	TabletType_replica TabletType = 0
	// PRIMARY is the primary server for the shard. Only PRIMARY allows DMLs.
	TabletType_primary TabletType = 1
	// RDONLY (old name) / BATCH (new name) is used to serve traffic for
	// long-running jobs. It is a separate type from REPLICA so
	// long-running queries don't affect web-like traffic.
	TabletType_read_only TabletType = 2
	TabletType_batch     TabletType = 2
)

// Enum value maps for TabletType.
var (
	TabletType_name = map[int32]string{
		0: "replica",
		1: "primary",
		2: "read_only",
		// Duplicate value: 2: "batch",
	}
	TabletType_value = map[string]int32{
		"replica":   0,
		"primary":   1,
		"read_only": 2,
		"batch":     2,
	}
)

func (x TabletType) Enum() *TabletType {
	p := new(TabletType)
	*p = x
	return p
}

func (x TabletType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TabletType) Descriptor() protoreflect.EnumDescriptor {
	return file_psdbconnect_v1alpha1_proto_enumTypes[0].Descriptor()
}

func (TabletType) Type() protoreflect.EnumType {
	return &file_psdbconnect_v1alpha1_proto_enumTypes[0]
}

func (x TabletType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TabletType.Descriptor instead.
func (TabletType) EnumDescriptor() ([]byte, []int) {
	return file_psdbconnect_v1alpha1_proto_rawDescGZIP(), []int{0}
}

type DeletedRow struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Result        *query.QueryResult     `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeletedRow) Reset() {
	*x = DeletedRow{}
	mi := &file_psdbconnect_v1alpha1_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeletedRow) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeletedRow) ProtoMessage() {}

func (x *DeletedRow) ProtoReflect() protoreflect.Message {
	mi := &file_psdbconnect_v1alpha1_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeletedRow.ProtoReflect.Descriptor instead.
func (*DeletedRow) Descriptor() ([]byte, []int) {
	return file_psdbconnect_v1alpha1_proto_rawDescGZIP(), []int{0}
}

func (x *DeletedRow) GetResult() *query.QueryResult {
	if x != nil {
		return x.Result
	}
	return nil
}

type UpdatedRow struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Before        *query.QueryResult     `protobuf:"bytes,1,opt,name=before,proto3" json:"before,omitempty"`
	After         *query.QueryResult     `protobuf:"bytes,2,opt,name=after,proto3" json:"after,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdatedRow) Reset() {
	*x = UpdatedRow{}
	mi := &file_psdbconnect_v1alpha1_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdatedRow) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdatedRow) ProtoMessage() {}

func (x *UpdatedRow) ProtoReflect() protoreflect.Message {
	mi := &file_psdbconnect_v1alpha1_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdatedRow.ProtoReflect.Descriptor instead.
func (*UpdatedRow) Descriptor() ([]byte, []int) {
	return file_psdbconnect_v1alpha1_proto_rawDescGZIP(), []int{1}
}

func (x *UpdatedRow) GetBefore() *query.QueryResult {
	if x != nil {
		return x.Before
	}
	return nil
}

func (x *UpdatedRow) GetAfter() *query.QueryResult {
	if x != nil {
		return x.After
	}
	return nil
}

type TableCursor struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Shard         string                 `protobuf:"bytes,1,opt,name=shard,proto3" json:"shard,omitempty"`
	Keyspace      string                 `protobuf:"bytes,2,opt,name=keyspace,proto3" json:"keyspace,omitempty"`
	Position      string                 `protobuf:"bytes,3,opt,name=position,proto3" json:"position,omitempty"`
	LastKnownPk   *query.QueryResult     `protobuf:"bytes,4,opt,name=last_known_pk,json=lastKnownPk,proto3" json:"last_known_pk,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TableCursor) Reset() {
	*x = TableCursor{}
	mi := &file_psdbconnect_v1alpha1_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TableCursor) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TableCursor) ProtoMessage() {}

func (x *TableCursor) ProtoReflect() protoreflect.Message {
	mi := &file_psdbconnect_v1alpha1_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TableCursor.ProtoReflect.Descriptor instead.
func (*TableCursor) Descriptor() ([]byte, []int) {
	return file_psdbconnect_v1alpha1_proto_rawDescGZIP(), []int{2}
}

func (x *TableCursor) GetShard() string {
	if x != nil {
		return x.Shard
	}
	return ""
}

func (x *TableCursor) GetKeyspace() string {
	if x != nil {
		return x.Keyspace
	}
	return ""
}

func (x *TableCursor) GetPosition() string {
	if x != nil {
		return x.Position
	}
	return ""
}

func (x *TableCursor) GetLastKnownPk() *query.QueryResult {
	if x != nil {
		return x.LastKnownPk
	}
	return nil
}

var File_psdbconnect_v1alpha1_proto protoreflect.FileDescriptor

const file_psdbconnect_v1alpha1_proto_rawDesc = "" +
	"\n" +
	"\x1apsdbconnect.v1alpha1.proto\x12\x14psdbconnect.v1alpha1\x1a\vquery.proto\"8\n" +
	"\n" +
	"DeletedRow\x12*\n" +
	"\x06result\x18\x01 \x01(\v2\x12.query.QueryResultR\x06result\"b\n" +
	"\n" +
	"UpdatedRow\x12*\n" +
	"\x06before\x18\x01 \x01(\v2\x12.query.QueryResultR\x06before\x12(\n" +
	"\x05after\x18\x02 \x01(\v2\x12.query.QueryResultR\x05after\"\x93\x01\n" +
	"\vTableCursor\x12\x14\n" +
	"\x05shard\x18\x01 \x01(\tR\x05shard\x12\x1a\n" +
	"\bkeyspace\x18\x02 \x01(\tR\bkeyspace\x12\x1a\n" +
	"\bposition\x18\x03 \x01(\tR\bposition\x126\n" +
	"\rlast_known_pk\x18\x04 \x01(\v2\x12.query.QueryResultR\vlastKnownPk*D\n" +
	"\n" +
	"TabletType\x12\v\n" +
	"\areplica\x10\x00\x12\v\n" +
	"\aprimary\x10\x01\x12\r\n" +
	"\tread_only\x10\x02\x12\t\n" +
	"\x05batch\x10\x02\x1a\x02\x10\x01BVZTgithub.com/planetscale/airbyte-source/proto/psdbconnect/v1alpha1;psdbconnectv1alpha1b\x06proto3"

var (
	file_psdbconnect_v1alpha1_proto_rawDescOnce sync.Once
	file_psdbconnect_v1alpha1_proto_rawDescData []byte
)

func file_psdbconnect_v1alpha1_proto_rawDescGZIP() []byte {
	file_psdbconnect_v1alpha1_proto_rawDescOnce.Do(func() {
		file_psdbconnect_v1alpha1_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_psdbconnect_v1alpha1_proto_rawDesc), len(file_psdbconnect_v1alpha1_proto_rawDesc)))
	})
	return file_psdbconnect_v1alpha1_proto_rawDescData
}

var file_psdbconnect_v1alpha1_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_psdbconnect_v1alpha1_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_psdbconnect_v1alpha1_proto_goTypes = []any{
	(TabletType)(0),           // 0: psdbconnect.v1alpha1.TabletType
	(*DeletedRow)(nil),        // 1: psdbconnect.v1alpha1.DeletedRow
	(*UpdatedRow)(nil),        // 2: psdbconnect.v1alpha1.UpdatedRow
	(*TableCursor)(nil),       // 3: psdbconnect.v1alpha1.TableCursor
	(*query.QueryResult)(nil), // 4: query.QueryResult
}
var file_psdbconnect_v1alpha1_proto_depIdxs = []int32{
	4, // 0: psdbconnect.v1alpha1.DeletedRow.result:type_name -> query.QueryResult
	4, // 1: psdbconnect.v1alpha1.UpdatedRow.before:type_name -> query.QueryResult
	4, // 2: psdbconnect.v1alpha1.UpdatedRow.after:type_name -> query.QueryResult
	4, // 3: psdbconnect.v1alpha1.TableCursor.last_known_pk:type_name -> query.QueryResult
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_psdbconnect_v1alpha1_proto_init() }
func file_psdbconnect_v1alpha1_proto_init() {
	if File_psdbconnect_v1alpha1_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_psdbconnect_v1alpha1_proto_rawDesc), len(file_psdbconnect_v1alpha1_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_psdbconnect_v1alpha1_proto_goTypes,
		DependencyIndexes: file_psdbconnect_v1alpha1_proto_depIdxs,
		EnumInfos:         file_psdbconnect_v1alpha1_proto_enumTypes,
		MessageInfos:      file_psdbconnect_v1alpha1_proto_msgTypes,
	}.Build()
	File_psdbconnect_v1alpha1_proto = out.File
	file_psdbconnect_v1alpha1_proto_goTypes = nil
	file_psdbconnect_v1alpha1_proto_depIdxs = nil
}
