agents:
  queue: "private"

steps:
  - name: "go build"
    env:
      DOCKER_BUILDKIT: 1
    plugins:
      - docker-compose#v3.7.0:
          run: app

  - name: "Tests"
    label: "Tests"
    command: "go test -race -v ./..."
    env:
      DOCKER_BUILDKIT: 1
    plugins:
      - docker-compose#v3.9.0:
          run: ci

  - name: "go vet"
    label: "Tests"
    command: "go vet ./..."
    env:
      DOCKER_BUILDKIT: 1
    plugins:
      - docker-compose#v3.9.0:
          run: ci

  - name: "staticcheck"
    label: "Tests"
    command: "go install honnef.co/go/tools/cmd/staticcheck@latest && staticcheck ./..."
    env:
      DOCKER_BUILDKIT: 1
    plugins:
      - docker-compose#v3.9.0:
          run: ci

  - name: "Verify dependency licenses %n"
    command: "go get -v ./... && license_finder"
    env:
      DOCKER_BUILDKIT: 1
    plugins:
      - docker-compose#v3.9.0:
          run: ci

  - wait

  - block: ":rocket: Release !"
    branches: "main"

  - command: script/bump-version.sh
    if: build.branch == "main"
    label: ":arrow_up_small: Bump & tag version"

  - wait

  - label: ":github: Publishing artifacts"
    if: build.branch == "main"
    command: script/release.sh
    plugins:
      - docker#v3.8.0:
          image: "golang:1.18"
          propagate-environment: true
          environment:
            - "GITHUB_TOKEN"
            - "DOCKER_USERNAME"
            - "DOCKER_PASSWORD"
          volumes:
            - "/var/run/docker.sock:/var/run/docker.sock"